### ISSUE TITLE
pongo2模板

### ISSUE THREAD

**Issue by 0xfnzero** [Lihuanghe/SqlTemplateParser#3]
模板引擎不错，功能挺强大的，就是语法有点奇怪，可以参考下pongo2模板
https://github.com/flosch/pongo2

![image](https://user-images.githubusercontent.com/2081812/57006361-bac20780-6c12-11e9-90de-f977ddaa2e6b.png)

**Comment by Lihuanghe** [comment]
`${abc}`这种写法是继承shell. 因为这个工具诞生就是为了替换以前几百个shell脚本写的报表。为了兼容，了了减少重写sql的工作量，所以才有了这么个语法。
